Importiert das Paket `numpy` unter dem Alias `np`.

In [3]:
import numpy as np

Definiert eine Liste `l` mit den Elementen `1,2,3`. Ist das ein Array?

In [25]:
l = [1,2,3]
print(l)
type(l)

[1, 2, 3]


list

Erzeugt ein 1D-Array (Vektor) `v` mit den Werte `3,2,1`.

In [9]:
v = np.array([3,2,1])
v

array([3, 2, 1])

Welchen Elementtyp und welche Shape hat `v`?

In [27]:
print(type(v))
print(v.dtype)
v.shape

<class 'numpy.ndarray'>
int64


(3,)

Addiert den Vektor `v` mit sich selbst (v+v).

In [40]:
print(v+v)

[14 10  6]


Addiert auf jeden Wert aus `v` den Wert `1` hinzu.

In [39]:
print(v)
print(v + 1)

[7 5 3]
[8 6 4]


Kann die Liste `l` mit sich selbst addiert werden (l+l)?

In [34]:
l + l

[1, 2, 3, 1, 2, 3]

Wie kann man `l` mit sich selbst addieren?

In [33]:
np.add(l,l)

array([2, 4, 6])

Wie lauten die Mittelwerte von `l` und `v`?

In [32]:
np.mean(l)

2.0

In [23]:
v.mean()

5.0